/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type PostReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "post"
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type Homepage = {
  _id: string
  _type: "homepage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  featuredPost?: PostReference
  heroTitle?: string
  heroTagline?: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  ctaText?: string
  newsletterTitle?: string
  newsletterDescription?: string
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Footer = {
  _id: string
  _type: "footer"
  _createdAt: string
  _updatedAt: string
  _rev: string
  text?: string
  githubUrl?: string
}

export type Navbar = {
  _id: string
  _type: "navbar"
  _createdAt: string
  _updatedAt: string
  _rev: string
  brandLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  links?: Array<{
    label?: string
    href?: string
    _key: string
  }>
  githubUrl?: string
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
      _type: "image"
      _key: string
    }
  | ({
      _key: string
    } & Code)
>

export type Category = {
  _id: string
  _type: "category"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type AuthorReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "author"
}

export type CategoryReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "category"
}

export type Post = {
  _id: string
  _type: "post"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  excerpt?: string
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  author?: AuthorReference
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  publishedAt?: string
  body?: BlockContent
}

export type Author = {
  _id: string
  _type: "author"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  headline?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  bio?: string
  socials?: Array<{
    platform?: "linkedin" | "github" | "twitter" | "website" | "email" | "youtube"
    url?: string
    _type: "social"
    _key: string
  }>
}

export type MediaTag = {
  _id: string
  _type: "media.tag"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type Code = {
  _type: "code"
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | PostReference
  | SanityImageAssetReference
  | Homepage
  | SanityImageCrop
  | SanityImageHotspot
  | Footer
  | Navbar
  | BlockContent
  | Category
  | Slug
  | AuthorReference
  | CategoryReference
  | Post
  | Author
  | MediaTag
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/sanity/lib/queries/article.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {      _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage,  "author": author->{    name,    "slug": slug.current,    headline,    image  },  "categories": categories[]->{    _id,    title,    "slug": slug.current  }  }
export type AllPostsQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
  excerpt: string | null
  publishedAt: string | null
  mainImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  } | null
  author: {
    name: string | null
    slug: string | null
    headline: string | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: "image"
    } | null
  } | null
  categories: Array<{
    _id: string
    title: string | null
    slug: string | null
  }> | null
}>

// Source: src/sanity/lib/queries/article.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {      _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage,  "author": author->{    name,    "slug": slug.current,    headline,    image  },  "categories": categories[]->{    _id,    title,    "slug": slug.current  },    body  }
export type PostBySlugQueryResult = {
  _id: string
  title: string | null
  slug: string | null
  excerpt: string | null
  publishedAt: string | null
  mainImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  } | null
  author: {
    name: string | null
    slug: string | null
    headline: string | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: "image"
    } | null
  } | null
  categories: Array<{
    _id: string
    title: string | null
    slug: string | null
  }> | null
  body: BlockContent | null
} | null

// Source: src/sanity/lib/queries/article.ts
// Variable: postSlugsQuery
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type PostSlugsQueryResult = Array<{
  slug: string | null
}>

// Source: src/sanity/lib/queries/article.ts
// Variable: authorProfileQuery
// Query: *[_type == "author"] | order(_createdAt asc)[0] {    name,    headline,    bio,    image,    socials  }
export type AuthorProfileQueryResult = {
  name: string | null
  headline: string | null
  bio: string | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  } | null
  socials: Array<{
    platform?: "email" | "github" | "linkedin" | "twitter" | "website" | "youtube"
    url?: string
    _type: "social"
    _key: string
  }> | null
} | null

// Source: src/sanity/lib/queries/article.ts
// Variable: allCategoriesQuery
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    "count": count(*[_type == "post" && references(^._id)])  }
export type AllCategoriesQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
  count: number
}>

// Source: src/sanity/lib/queries/article.ts
// Variable: homepageDataQuery
// Query: {    "homepage": *[_type == "homepage" && _id == "homepage"][0] {      heroTitle,      heroTagline,      heroImage,      ctaText,      newsletterTitle,      newsletterDescription,      "featuredPost": featuredPost->{          _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage,  "author": author->{    name,    "slug": slug.current,    headline,    image  },  "categories": categories[]->{    _id,    title,    "slug": slug.current  }      }    },    "recentPosts": *[_type == "post" && defined(slug.current) && _id != *[_type == "homepage" && _id == "homepage"][0].featuredPost._ref] | order(publishedAt desc)[0...13] {        _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage,  "author": author->{    name,    "slug": slug.current,    headline,    image  },  "categories": categories[]->{    _id,    title,    "slug": slug.current  }    },    "author": *[_type == "author"] | order(_createdAt asc)[0] {      name,      headline,      bio,      image,      socials,      "postCount": count(*[_type == "post" && references(^._id)])    },    "categories": *[_type == "category"] | order(title asc) {      _id,      title,      "slug": slug.current,      "count": count(*[_type == "post" && references(^._id)])    }  }
export type HomepageDataQueryResult = {
  homepage: {
    heroTitle: string | null
    heroTagline: string | null
    heroImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: "image"
    } | null
    ctaText: string | null
    newsletterTitle: string | null
    newsletterDescription: string | null
    featuredPost: {
      _id: string
      title: string | null
      slug: string | null
      excerpt: string | null
      publishedAt: string | null
      mainImage: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: "image"
      } | null
      author: {
        name: string | null
        slug: string | null
        headline: string | null
        image: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: "image"
        } | null
      } | null
      categories: Array<{
        _id: string
        title: string | null
        slug: string | null
      }> | null
    } | null
  } | null
  recentPosts: Array<{
    _id: string
    title: string | null
    slug: string | null
    excerpt: string | null
    publishedAt: string | null
    mainImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: "image"
    } | null
    author: {
      name: string | null
      slug: string | null
      headline: string | null
      image: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: "image"
      } | null
    } | null
    categories: Array<{
      _id: string
      title: string | null
      slug: string | null
    }> | null
  }>
  author: {
    name: string | null
    headline: string | null
    bio: string | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: "image"
    } | null
    socials: Array<{
      platform?: "email" | "github" | "linkedin" | "twitter" | "website" | "youtube"
      url?: string
      _type: "social"
      _key: string
    }> | null
    postCount: number
  } | null
  categories: Array<{
    _id: string
    title: string | null
    slug: string | null
    count: number
  }>
}

// Source: src/sanity/lib/queries/layout.ts
// Variable: navbarQuery
// Query: *[_type == "navbar"][0] {    brandLogo {      asset->{        url      },      alt    },    brandName,    links[] {      label,      href    },    githubUrl  }
export type NavbarQueryResult = {
  brandLogo: {
    asset: {
      url: string | null
    } | null
    alt: string | null
  } | null
  brandName: null
  links: Array<{
    label: string | null
    href: string | null
  }> | null
  githubUrl: string | null
} | null

// Source: src/sanity/lib/queries/layout.ts
// Variable: footerQuery
// Query: *[_type == "footer"][0] {    text,    githubUrl  }
export type FooterQueryResult = {
  text: string | null
  githubUrl: string | null
} | null

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage,\n  "author": author->{\n    name,\n    "slug": slug.current,\n    headline,\n    image\n  },\n  "categories": categories[]->{\n    _id,\n    title,\n    "slug": slug.current\n  }\n\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage,\n  "author": author->{\n    name,\n    "slug": slug.current,\n    headline,\n    image\n  },\n  "categories": categories[]->{\n    _id,\n    title,\n    "slug": slug.current\n  }\n,\n    body\n  }\n': PostBySlugQueryResult
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': PostSlugsQueryResult
    '\n  *[_type == "author"] | order(_createdAt asc)[0] {\n    name,\n    headline,\n    bio,\n    image,\n    socials\n  }\n': AuthorProfileQueryResult
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    "count": count(*[_type == "post" && references(^._id)])\n  }\n': AllCategoriesQueryResult
    '\n  {\n    "homepage": *[_type == "homepage" && _id == "homepage"][0] {\n      heroTitle,\n      heroTagline,\n      heroImage,\n      ctaText,\n      newsletterTitle,\n      newsletterDescription,\n      "featuredPost": featuredPost->{\n        \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage,\n  "author": author->{\n    name,\n    "slug": slug.current,\n    headline,\n    image\n  },\n  "categories": categories[]->{\n    _id,\n    title,\n    "slug": slug.current\n  }\n\n      }\n    },\n    "recentPosts": *[_type == "post" && defined(slug.current) && _id != *[_type == "homepage" && _id == "homepage"][0].featuredPost._ref] | order(publishedAt desc)[0...13] {\n      \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage,\n  "author": author->{\n    name,\n    "slug": slug.current,\n    headline,\n    image\n  },\n  "categories": categories[]->{\n    _id,\n    title,\n    "slug": slug.current\n  }\n\n    },\n    "author": *[_type == "author"] | order(_createdAt asc)[0] {\n      name,\n      headline,\n      bio,\n      image,\n      socials,\n      "postCount": count(*[_type == "post" && references(^._id)])\n    },\n    "categories": *[_type == "category"] | order(title asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      "count": count(*[_type == "post" && references(^._id)])\n    }\n  }\n': HomepageDataQueryResult
    '\n  *[_type == "navbar"][0] {\n    brandLogo {\n      asset->{\n        url\n      },\n      alt\n    },\n    brandName,\n    links[] {\n      label,\n      href\n    },\n    githubUrl\n  }\n': NavbarQueryResult
    '\n  *[_type == "footer"][0] {\n    text,\n    githubUrl\n  }\n': FooterQueryResult
  }
}
